# Generated by Django 5.2.1 on 2025-05-23 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_holding', models.CharField(max_length=255, verbose_name='Nome Holding')),
                ('cnpj', models.CharField(max_length=30, verbose_name='CNPJ')),
                ('status', models.CharField(choices=[('pending', 'Em análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], max_length=30, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
