# Generated by Django 5.2.1 on 2025-05-23 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo do Documento')),
                ('url_arquivo', models.CharField(max_length=200, verbose_name='URL do Arquivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], max_length=30, verbose_name='Status')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('holding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_holding', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
    ]
