# Generated by Django 5.2.1 on 2025-05-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0002_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='holding_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_holding', to='holding.holding'),
        ),
    ]
