# Generated by Django 5.2.1 on 2025-05-23 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0003_alter_documento_holding_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField(max_length=1000, verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('alert', 'Alerta'), ('update', 'Atualização'), ('request', 'Solicitação')], max_length=50, verbose_name='Tipo de Notificação')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('is_lida', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etapa', models.CharField(max_length=50, verbose_name='Etapa')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('progress', 'Em andamento'), ('completed', 'Concluído')], max_length=30, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('holding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_holding', to='holding.holding')),
            ],
        ),
    ]
