# Generated by Django 5.2.1 on 2025-05-23 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('retirement', 'Aposentadoria'), ('travel', 'Viagem'), ('real_estate', 'Imóvel'), ('vehicle', 'Veículo'), ('education', 'Educação'), ('health', 'Saúde'), ('business', 'Negócio'), ('other', 'Outro')], max_length=100, verbose_name='Categoria')),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alvo')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atual')),
                ('data_alvo', models.DateField(verbose_name='Data Alvo')),
                ('aporte_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aporte Mensal')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processo'), ('completed', 'Concluído')], default='pending', max_length=100, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
